#
# Copyright (c) 2009 rPath, Inc.
#
# This program is distributed under the terms of the MIT License as found 
# in a file called LICENSE. If it is not present, the license
# is always available at http://www.opensource.org/licenses/mit-license.php.
#
# This program is distributed in the hope that it will be useful, but
# without any warranty; without even the implied warranty of merchantability
# or fitness for a particular purpose. See the MIT License for full details.
#

build: default-build as-build

install: default-install as-install

clean: default-clean as-clean

test: default-test


export TOPDIR=$(shell pwd)/../..
include $(TOPDIR)/Make.rules
include $(TOPDIR)/Make.defs
